service: rerundependabot
variablesResolutionMode: 20210326

frameworkVersion: '2'

plugins:
  - serverless-plugin-scripts
  - serverless-stack-termination-protection
  - serverless-s3-bucket-helper
  - serverless-iam-helper

provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  iam:
    role:
      path: ${self:custom.iamPath}
      permissionsBoundary: ${self:custom.iamPermissionsBoundaryPolicy}

custom:
  stage: ${opt:stage, self:provider.stage}
  iamPath: ${env:IAM_PATH, "/"}
  ghToken: ${env:DEPENDABOT_BOT_TOKEN}
  iamPermissionsBoundaryPolicy: ${env:FULL_IAM_PERMISSIONS_BOUNDARY_POLICY, ""}
  serverlessTerminationProtection:
    stages:
      - dev
      - val
      - prod
      - main
  scripts:
    hooks:
      # curl down the artifacts for deployment
      package:initialize: |
        echo "Curling Down lambda-dependabot"
        curl -L https://github.com/trussworks/lambda-dependabot/releases/download/v0.0.1/lambda-dependabot.zip --output lambda-dependabot.zip
        curl -L https://github.com/trussworks/lambda-dependabot/releases/download/v0.0.1/pygh-layer.zip --output pygh-layer.zip

package:
  individually: true

layers:
  pygithub:
    package:
      artifact: pygh-layer.zip

functions:
  rerun-dependabot:
    runtime: python3.8
    handler: lambda_function.lambda_handler
    layers:
      - { Ref: PygithubLambdaLayer }
    events:
      - schedule:
          name: re-run-dependabot-event
          description: 'time to check if there are dependabot prs to retry'
          rate: rate(20 minutes)
    description: Reruns dependabot github actions that fail for lack of secrets access
    timeout: 30
    environment:
      GITHUB_ACTOR: dependabot[bot]
      GITHUB_REPO: cmsgov/managed-care-review
      GITHUB_TOKEN: ${self:custom.ghToken}
      WORKFLOW_NAME: Deploy
      JOB_NAME: deploy
      STEP_NAME: Check for secrets
      TRIGGER_STRING: SECRETS MISSING
      LOG_ZIP: /tmp/lambda_logs.zip
      GITHUB_PULL_LABEL: reran
      GITHUB_ENABLE_COMMENT: true
      DRY_RUN: false

    package:
      artifact: lambda-dependabot.zip
