version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 4
    package-name-patterns:
      - '@aws-sdk/*'
    ignore:
      - dependency-name: '@types/node'
        versions: ['>14.999'] # I think this is how we don't ever go above 14?
