version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/tests/nightwatch'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/services/app-api'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/services/app-graphql'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/services/app-web'
    schedule:
      interval: 'weekly'
