version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: '@types/node'
        versions: ['>14.999'] # I think this is how we don't ever go above 14?

  - package-ecosystem: 'npm'
    directory: '/tests/nightwatch'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 2

  - package-ecosystem: 'npm'
    directory: '/services/app-api'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 2

  - package-ecosystem: 'npm'
    directory: '/services/app-graphql'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 2

  - package-ecosystem: 'npm'
    directory: '/services/app-web'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 2
