version: '3'
services:
  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - '16686:16686'
      - '14268'
      - '14250:14250'

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ['--config=/etc/otel-collector-config.yaml']
    volumes:
      - ${PWD}/otel-collector-config.yml:/etc/otel-collector-config.yaml
    ports:
      - '4318:4318'
      - '4317:4317'
      - '55680:55680'
    depends_on:
      - jaeger-all-in-one
