name: 'Get Changed Services'
description: 'Finds services on a PR branch that need to be deployed'
inputs:
  branchName:
    description: 'The current branch that we are deploying'
    required: true
outputs:
  changed-services:
    description: 'An array of services that need to be deployed'
runs:
  using: 'node16'
  main: 'index.js'
