# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: database

plugins:
  - serverless-dynamodb-local

custom:
  stage: ${opt:stage, self:provider.stage}
  draftSubmissionsTableName: ${self:custom.stage}-draft-submissions
  tableName: ${self:custom.stage}-amendments
  dynamodb:
    stages:
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev

resources:
  Resources:
    DraftSubmissionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.draftSubmissionsTableName}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: stateCode
            AttributeType: S
          - AttributeName: stateNumber
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: StateStateNumberIndex
            KeySchema:
              - AttributeName: stateCode
                KeyType: HASH
              - AttributeName: stateNumber
                KeyType: RANGE
            Projection:
              ProjectionType: KEYS_ONLY
          - IndexName: StateStateNumberAllIndex
            KeySchema:
              - AttributeName: stateCode
                KeyType: HASH
              - AttributeName: stateNumber
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        # Set the capacity to auto-scale
        BillingMode: PAY_PER_REQUEST
    AmendmentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: amendmentId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: amendmentId
            KeyType: RANGE
        # Set the capacity to auto-scale
        BillingMode: PAY_PER_REQUEST
    AmendmentsAtomicCounterTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}-atomic-counter
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        # Set the capacity to auto-scale
        BillingMode: PAY_PER_REQUEST
  Outputs:
    DraftSubmissionsTableArn:
      Value: !GetAtt DraftSubmissionsTable.Arn
    DraftSubmissionsTableStreamArn:
      Value: !GetAtt DraftSubmissionsTable.StreamArn
    AmendmentsTableName:
      Value:
        Ref: AmendmentsTable
    AmendmentsTableArn:
      Value: !GetAtt AmendmentsTable.Arn
    AmendmentsTableStreamArn:
      Value: !GetAtt AmendmentsTable.StreamArn
    AmendmentsAtomicCounterTableName:
      Value:
        Ref: AmendmentsAtomicCounterTable
    AmendmentsAtomicCounterTableArn:
      Value: !GetAtt AmendmentsAtomicCounterTable.Arn
    Region:
      Value:
        Ref: AWS::Region
