service: database

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

plugins:
  - serverless-dynamodb-local
  - serverless-stack-termination-protection
  - serverless-s3-bucket-helper

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  draftSubmissionsTableName: ${self:custom.stage}-draft-submissions
  tableName: ${self:custom.stage}-amendments
  dynamodb:
    stages:
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true
  serverlessTerminationProtection:
    stages:
      - dev
      - val
      - prod
      - main

resources:
  Resources:
    DraftSubmissionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.draftSubmissionsTableName}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: stateCode
            AttributeType: S
          - AttributeName: stateNumber
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: StateStateNumberAllIndex
            KeySchema:
              - AttributeName: stateCode
                KeyType: HASH
              - AttributeName: stateNumber
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST # Set the capacity to auto-scale
    AmendmentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: amendmentId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: amendmentId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST # Set the capacity to auto-scale
    AmendmentsAtomicCounterTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}-atomic-counter
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        # Set the capacity to auto-scale
        BillingMode: PAY_PER_REQUEST
  Outputs:
    DraftSubmissionsTableArn:
      Value: !GetAtt DraftSubmissionsTable.Arn
    DraftSubmissionsTableStreamArn:
      Value: !GetAtt DraftSubmissionsTable.StreamArn
    AmendmentsTableName:
      Value: !Ref AmendmentsTable
    AmendmentsTableArn:
      Value: !GetAtt AmendmentsTable.Arn
    AmendmentsTableStreamArn:
      Value: !GetAtt AmendmentsTable.StreamArn
    AmendmentsAtomicCounterTableName:
      Value: !Ref AmendmentsAtomicCounterTable
    AmendmentsAtomicCounterTableArn:
      Value: !GetAtt AmendmentsAtomicCounterTable.Arn
    Region:
      Value: !Sub ${AWS::Region}
