service: uploads

frameworkVersion: '^3.19.0'

plugins:
  - serverless-offline-ssm
  - serverless-plugin-scripts
  - serverless-s3-local
  - serverless-offline
  - serverless-stack-termination-protection
  - serverless-idempotency-helper
  - serverless-iam-helper
  - serverless-webpack

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iam:
    role:
      path: ${ssm:/configuration/iam/path, "/"}
      permissionsBoundary: ${ssm:/configuration/iam/full_permissions_boundary_policy}
      statements:
        - Effect: 'Allow'
          Action:
            - s3:GetObject
            - s3:GetObjectTagging
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:PutObjectTagging
            - s3:PutObjectVersionTagging
            - s3:DeleteObject
            - s3:ListBucket
          Resource:
            - !Sub arn:aws:s3:::${self:service}-${sls:stage}-uploads-${AWS::AccountId}/*
            - !Sub arn:aws:s3:::${self:service}-${sls:stage}-avscan-${AWS::AccountId}/*
            - !Sub arn:aws:s3:::${self:service}-${sls:stage}-qa-${AWS::AccountId}/*
        - Effect: 'Allow'
          Action:
            - s3:ListBucket
          Resource:
            - !Sub arn:aws:s3:::${self:service}-${sls:stage}-uploads-${AWS::AccountId}
            - !Sub arn:aws:s3:::${self:service}-${sls:stage}-avscan-${AWS::AccountId}
            - !Sub arn:aws:s3:::${self:service}-${sls:stage}-qa-${AWS::AccountId}
        - Effect: 'Allow'
          Action:
            - lambda:InvokeFunction
          Resource:
            - !Sub arn:aws:lambda:${self:provider.region}:${AWS::AccountId}:function:${self:service}-${sls:stage}-avAuditFiles

custom:
  region: ${aws:region}
  reactAppOtelCollectorUrl: ${env:REACT_APP_OTEL_COLLECTOR_URL, ssm:/configuration/react_app_otel_collector_url}
  webpack:
    webpackConfig: webpack.config.js
    packager: yarn
    packagerOptions:
      lockFile: ../../yarn.lock
  scripts:
    hooks:
      # This script is run locally when running 'serverless deploy'
      package:initialize: |
        set -e
        curl -L --output lambda_layer.zip https://github.com/CMSgov/lambda-clamav-layer/releases/download/0.7/lambda_layer.zip
      deploy:finalize: |
        rm lambda_layer.zip
        serverless invoke --stage ${sls:stage} --function avDownloadDefinitions -t Event
  vpcId: ${ssm:/configuration/${sls:stage}/vpc/id, ssm:/configuration/default/vpc/id}
  sgId: ${ssm:/configuration/${sls:stage}/vpc/sg/id, ssm:/configuration/default/vpc/sg/id}
  privateSubnets:
    - ${ssm:/configuration/${sls:stage}/vpc/subnets/private/a/id, ssm:/configuration/default/vpc/subnets/private/a/id}
    - ${ssm:/configuration/${sls:stage}/vpc/subnets/private/b/id, ssm:/configuration/default/vpc/subnets/private/b/id}
    - ${ssm:/configuration/${sls:stage}/vpc/subnets/private/c/id, ssm:/configuration/default/vpc/subnets/private/c/id}
  publicSubnetA: ${ssm:/configuration/${sls:stage}/vpc/subnets/public/a/id, ssm:/configuration/default/vpc/subnets/public/a/id}
  serverless-offline-ssm:
    stages:
      - local
      - offline
    ssm:
      '/configuration/iam/full_permissions_boundary_policy': 'arn:aws:iam::local:policy/local/developer-boundary-policy'
  s3:
    # address: 127.0.0.1 # this started defaulting to ipv6 which prevented tests from connecting
    # when vhostBuckets are enabled all non-localhost hostnames are re-written as buckets
    # setting this false allows the workaround for docker to work.
    vhostBuckets: false
    directory: ./local_buckets
    cors: ./local_cors.xml
    buckets:
      - local-uploads # This is a little silly, but I've spent enough time on it.
        # the serverless-s3-local plugin starts any bucket with a BucketName
        # the attachments bucket has no name, so we need to make one up on our own
      - local-qa
      - test-uploads
      - test-audit
      - test-av-definitions
  serverlessTerminationProtection:
    stages:
      - dev
      - val
      - prod
      - main

layers:
  clamAv:
    package:
      artifact: lambda_layer.zip

functions:
  avScan:
    handler: src/lambdas/index.avScan
    name: ${self:service}-${sls:stage}-avScan
    timeout: 300 # 300 seconds = 5 minutes. Average scan is 25 seconds.
    memorySize: 4096
    ephemeralStorageSize: 1024
    layers:
      - !Ref ClamAvLambdaLayer
      - arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-nodejs-amd64-ver-1-18-1:1
    vpc:
      securityGroupIds: ${self:custom.sgId}
      subnetIds: ${self:custom.privateSubnets}
    environment:
      stage: ${sls:stage}
      CLAMAV_BUCKET_NAME: !Ref ClamDefsBucket
      PATH_TO_AV_DEFINITIONS: 'lambda/s3-antivirus/av-definitions'
      AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-handler
      OPENTELEMETRY_COLLECTOR_CONFIG_FILE: /var/task/collector.yml
      REACT_APP_OTEL_COLLECTOR_URL: ${self:custom.reactAppOtelCollectorUrl}

  avDownloadDefinitions:
    handler: src/lambdas/index.avDownloadDefinitions
    events:
      - schedule: cron(0 */6 * * ? *)
    timeout: 300 # 300 seconds = 5 minutes
    memorySize: 1024
    layers:
      - !Ref ClamAvLambdaLayer
      - arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-nodejs-amd64-ver-1-18-1:1
    environment:
      stage: ${sls:stage}
      CLAMAV_BUCKET_NAME: !Ref ClamDefsBucket
      PATH_TO_AV_DEFINITIONS: 'lambda/s3-antivirus/av-definitions'
      AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-handler
      OPENTELEMETRY_COLLECTOR_CONFIG_FILE: /var/task/collector.yml
      REACT_APP_OTEL_COLLECTOR_URL: ${self:custom.reactAppOtelCollectorUrl}

  avAuditUploads:
    handler: src/lambdas/index.avAuditUploads
    timeout: 300 # 300 seconds = 5 minutes. Average scan is 25 seconds.
    maximumRetryAttempts: 0
    layers:
      - !Ref ClamAvLambdaLayer
      - arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-nodejs-amd64-ver-1-18-1:1
    environment:
      stage: ${sls:stage}
      AUDIT_BUCKET_NAME: !Ref DocumentUploadsBucket
      CLAMAV_BUCKET_NAME: !Ref ClamDefsBucket
      PATH_TO_AV_DEFINITIONS: 'lambda/s3-antivirus/av-definitions'
      LIST_INFECTED_FILES_LAMBDA_NAME: ${self:functions.avAuditFiles.name}
      AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-handler
      OPENTELEMETRY_COLLECTOR_CONFIG_FILE: /var/task/collector.yml
      REACT_APP_OTEL_COLLECTOR_URL: ${self:custom.reactAppOtelCollectorUrl}

  avAuditFiles:
    handler: src/lambdas/index.avAuditFiles
    name: ${self:service}-${sls:stage}-avAuditFiles
    timeout: 300 # 300 seconds = 5 minutes. Average scan is 25 seconds.
    memorySize: 2048
    ephemeralStorageSize: 1024
    maximumRetryAttempts: 0
    layers:
      - !Ref ClamAvLambdaLayer
      - arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-nodejs-amd64-ver-1-18-1:1
    environment:
      stage: ${sls:stage}
      AUDIT_BUCKET_NAME: !Ref DocumentUploadsBucket
      CLAMAV_BUCKET_NAME: !Ref ClamDefsBucket
      PATH_TO_AV_DEFINITIONS: 'lambda/s3-antivirus/av-definitions'
      AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-handler
      OPENTELEMETRY_COLLECTOR_CONFIG_FILE: /var/task/collector.yml
      REACT_APP_OTEL_COLLECTOR_URL: ${self:custom.reactAppOtelCollectorUrl}

resources:
  Resources:
    DocumentUploadsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub ${self:service}-${sls:stage}-uploads-${AWS::AccountId}
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        CorsConfiguration: # Set the CORS policy
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000
              ExposedHeaders:
                - ETag
        NotificationConfiguration:
          LambdaConfigurations:
            - Event: s3:ObjectCreated:*
              Function: !GetAtt AvScanLambdaFunction.Arn
      DependsOn: LambdaInvokePermission

    DocumentsUploadsBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref DocumentUploadsBucket
        PolicyDocument:
          Statement:
            - Action:
                - 's3:GetObject'
              Effect: 'Deny'
              Resource:
                - !Sub ${DocumentUploadsBucket.Arn}/*
              Principal: '*'
              Condition:
                StringNotEquals:
                  s3:ExistingObjectTag/virusScanStatus:
                    - 'CLEAN'
                  s3:ExistingObjectTag/contentsPreviouslyScanned:
                    - 'TRUE'
                  aws:PrincipalArn: !GetAtt IamRoleLambdaExecution.Arn
            - Action: 's3:PutObject'
              Effect: Deny
              Principal: '*'
              NotResource:
                - !Sub ${DocumentUploadsBucket.Arn}/*.csv
                - !Sub ${DocumentUploadsBucket.Arn}/*.doc
                - !Sub ${DocumentUploadsBucket.Arn}/*.docx
                - !Sub ${DocumentUploadsBucket.Arn}/*.pdf
                - !Sub ${DocumentUploadsBucket.Arn}/*.txt
                - !Sub ${DocumentUploadsBucket.Arn}/*.xls
                - !Sub ${DocumentUploadsBucket.Arn}/*.xlsx
                - !Sub ${DocumentUploadsBucket.Arn}/*.zip
                - !Sub ${DocumentUploadsBucket.Arn}/*.xlsm
                - !Sub ${DocumentUploadsBucket.Arn}/*.xltm
                - !Sub ${DocumentUploadsBucket.Arn}/*.xlam
            - Effect: Deny
              Action: 's3:*'
              Principal: '*'
              Condition:
                Bool:
                  'aws:SecureTransport': false
              Resource:
                - !Sub ${DocumentUploadsBucket.Arn}
                - !Sub ${DocumentUploadsBucket.Arn}/*
              Sid: DenyUnencryptedConnections

    LambdaInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: !GetAtt AvScanLambdaFunction.Arn
        Action: lambda:InvokeFunction
        Principal: s3.amazonaws.com
        SourceAccount: !Sub ${AWS::AccountId}
        SourceArn: !Sub arn:aws:s3:::${self:service}-${sls:stage}-uploads-${AWS::AccountId}

    ClamDefsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub ${self:service}-${sls:stage}-avscan-${AWS::AccountId}
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        AccessControl: Private
    ClamsDefsBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref ClamDefsBucket
        PolicyDocument:
          Statement:
            - Effect: Deny
              Action: 's3:*'
              Principal: '*'
              Condition:
                Bool:
                  'aws:SecureTransport': false
              Resource:
                - !Sub ${ClamDefsBucket.Arn}
                - !Sub ${ClamDefsBucket.Arn}/*
              Sid: DenyUnencryptedConnections

    QAUploadsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub ${self:service}-${sls:stage}-qa-${AWS::AccountId}
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        CorsConfiguration: # Set the CORS policy
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000
              ExposedHeaders:
                - ETag
        NotificationConfiguration:
          LambdaConfigurations:
            - Event: s3:ObjectCreated:*
              Function: !GetAtt AvScanLambdaFunction.Arn
      DependsOn: QAInvokePermission

    QAInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: !GetAtt AvScanLambdaFunction.Arn
        Action: lambda:InvokeFunction
        Principal: s3.amazonaws.com
        SourceAccount: !Sub ${AWS::AccountId}
        SourceArn: !Sub arn:aws:s3:::${self:service}-${sls:stage}-qa-${AWS::AccountId}

    QAUploadsBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref QAUploadsBucket
        PolicyDocument:
          Statement:
            - Action:
                - 's3:GetObject'
              Effect: 'Deny'
              Resource:
                - !Sub ${QAUploadsBucket.Arn}/*
              Principal: '*'
              Condition:
                StringNotEquals:
                  s3:ExistingObjectTag/virusScanStatus:
                    - 'CLEAN'
                  s3:ExistingObjectTag/contentsPreviouslyScanned:
                    - 'TRUE'
                  aws:PrincipalArn: !GetAtt IamRoleLambdaExecution.Arn
            - Action: 's3:PutObject'
              Effect: Deny
              Principal: '*'
              NotResource:
                - !Sub ${QAUploadsBucket.Arn}/*.csv
                - !Sub ${QAUploadsBucket.Arn}/*.doc
                - !Sub ${QAUploadsBucket.Arn}/*.docx
                - !Sub ${QAUploadsBucket.Arn}/*.pdf
                - !Sub ${QAUploadsBucket.Arn}/*.txt
                - !Sub ${QAUploadsBucket.Arn}/*.xls
                - !Sub ${QAUploadsBucket.Arn}/*.xlsx
                - !Sub ${QAUploadsBucket.Arn}/*.zip
                - !Sub ${QAUploadsBucket.Arn}/*.xlsm
                - !Sub ${QAUploadsBucket.Arn}/*.xltm
                - !Sub ${QAUploadsBucket.Arn}/*.xlam
            - Effect: Deny
              Action: 's3:*'
              Principal: '*'
              Condition:
                Bool:
                  'aws:SecureTransport': false
              Resource:
                - !Sub ${QAUploadsBucket.Arn}
                - !Sub ${QAUploadsBucket.Arn}/*
              Sid: DenyUnencryptedConnections

    ClamAVSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Security group for ClamAV daemon
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 3310
            ToPort: 3310
            SourceSecurityGroupId: ${self:custom.sgId}

    ClamAVInstanceProfile:
      Type: AWS::IAM::InstanceProfile
      Properties:
        Path: /
        Roles:
          - !Ref ClamAVInstanceRole

    ClamAVInstanceRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ClamAVInstancePolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: '*'

    ClamAVInstance:
      Type: AWS::EC2::Instance
      Properties:
        InstanceType: t2.micro
        ImageId: ami-05bfc1ab11bfbf484
        KeyName: my-key-pair # Replace with your key pair name
        SecurityGroups:
          - !Ref ClamAVSecurityGroup
        IamInstanceProfile: !Ref ClamAVInstanceProfile
        Tags:
          - Key: mcr-vmuse
            Value: clamavd
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            sudo apt-get update
            sudo apt-get install -y clamav clamav-daemon
            sudo systemctl enable clamav-freshclam
            sudo systemctl start clamav-freshclam
            sudo systemctl enable clamav-daemon
            sudo systemctl start clamav-daemon

  Outputs:
    DocumentUploadsBucketName:
      Value: !Ref DocumentUploadsBucket
    DocumentUploadsBucketArn:
      Value: !GetAtt DocumentUploadsBucket.Arn
    QAUploadsBucketName:
      Value: !Ref QAUploadsBucket
    QAUploadsBucketArn:
      Value: !GetAtt QAUploadsBucket.Arn
    Region:
      Value: !Sub ${AWS::Region}
