name: 'Setup MC-Review environment'
description: 'Runs common tasks for setting up the build environment in GHA'

runs:
  using: 'composite'
  steps:
    - name: Get yarn cache directory path
      shell: bash
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'

    - name: Install yarn package
      shell: bash
      id: yarn-install
      run: yarn install --prefer-offline --frozen-lockfile --cache-folder ${{ steps.yarn-cache-dir-path.outputs.dir }}

    - name: set path
      shell: bash
      run: |
        echo "PATH=$(pwd)/node_modules/.bin/:$PATH" >> $GITHUB_ENV
