name: Promote to an environment

on:
  workflow_call:
    inputs:
      stage_name:
        required: true
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      aws_default_region:
        required: true
      iam_path:
        required: true
      full_iam_permissions_boundary_policy:
        required: true
      cloudfront_certificate_arn:
        required: false
      cloudfront_domain_name:
        required: false
      cloudfront_storybook_domain_name:
        required: false
      react_app_auth_mode:
        required: true
      ses_source_email_address:
        required: true
      ses_review_team_email_addresses:
        required: true
      route_53_hosted_zone_id:
        required: false
      route_53_domain_name:
        required: false
      okta_metadata_url:
        required: true

jobs:
  postgres:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup env
        uses: ./.github/actions/setup_env

      - name: deploy postgres
        id: deploy-postgres
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          AWS_DEFAULT_REGION: ${{ secrets.aws_default_region }}
          IAM_PATH: ${{ secrets.iam_path }}
          FULL_IAM_PERMISSIONS_BOUNDARY_POLICY: ${{ secrets.full_iam_permissions_boundary_policy }}
        run: |
          pushd services/postgres && npx serverless deploy --stage ${{ inputs.stage_name }}

  ui:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup env
        uses: ./.github/actions/setup_env

      - name: deploy ui
        id: deploy-ui
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          AWS_DEFAULT_REGION: ${{ secrets.aws_default_region }}
          IAM_PATH: ${{ secrets.iam_path }}
          ROUTE_53_HOSTED_ZONE_ID: ${{ secrets.route_53_hosted_zone_id }}
          ROUTE_53_DOMAIN_NAME: ${{ secrets.route_53_domain_name }}
          CLOUDFRONT_CERTIFICATE_ARN: ${{ secrets.cloudfront_certificate_arn }}
          CLOUDFRONT_DOMAIN_NAME: ${{ secrets.cloudfront_domain_name }}
        run: |
          pushd services/ui && npx serverless deploy --stage ${{ inputs.stage_name }}

  storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup env
        uses: ./.github/actions/setup_env

      - name: deploy storybook
        id: deploy-storybook
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          AWS_DEFAULT_REGION: ${{ secrets.aws_default_region }}
          IAM_PATH: ${{ secrets.iam_path }}
          ROUTE_53_HOSTED_ZONE_ID: ${{ secrets.route_53_hosted_zone_id }}
          ROUTE_53_DOMAIN_NAME: ${{ secrets.route_53_domain_name }}
          CLOUDFRONT_CERTIFICATE_ARN: ${{ secrets.cloudfront_certificate_arn }}
          CLOUDFRONT_STORYBOOK_DOMAIN_NAME: ${{ secrets.cloudfront_storybook_domain_name }}

        run: |
          pushd services/storybook && npx serverless deploy --stage ${{ inputs.stage_name }}

  uploads:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup env
        uses: ./.github/actions/setup_env

      - name: deploy uploads
        id: deploy-uploads
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          AWS_DEFAULT_REGION: ${{ secrets.aws_default_region }}
          FULL_IAM_PERMISSIONS_BOUNDARY_POLICY: ${{ secrets.full_iam_permissions_boundary_policy }}
          IAM_PATH: ${{ secrets.iam_path }}
        run: |
          pushd services/uploads && npx serverless deploy --stage ${{ inputs.stage_name }}
