name: Promote to an environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      stage_name:
        required: true
        type: string
      app_version:
        required: true
        type: string
      changed_services:
        required: true
        type: string
      aws_default_region:
        required: true
        type: string
    secrets:
      aws_account_id:
        required: true
      react_app_auth_mode:
        required: true
      nr_license_key:
        required: true

permissions:
  id-token: write

jobs:
  app-web:
    if: ${{ contains(inputs.changed_services, 'app-web') }}
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup_env

      - name: Get AWS credentials
        uses: ./.github/actions/get_aws_credentials
        with:
          region: ${{ inputs.aws_default_region }}
          account-id: ${{ secrets.aws_account_id }}
          stage-name: ${{ inputs.stage_name }}
          changed-services: ${{ inputs.changed_services }}

      - name: deploy app-web
        id: deploy-app-web
        working-directory: services/app-web
        env:
          NODE_OPTIONS: --max_old_space_size=6000
          REACT_APP_AUTH_MODE: ${{ secrets.react_app_auth_mode }}
        run: yarn install && npx serverless deploy --stage ${{ inputs.stage_name }}

  app-api:
    if: ${{ contains(inputs.changed_services, 'app-api') || contains(inputs.changed_services, 'app-proto') }}
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup_env

      - name: Get AWS credentials
        uses: ./.github/actions/get_aws_credentials
        with:
          region: ${{ inputs.aws_default_region }}
          account-id: ${{ secrets.aws_account_id }}
          stage-name: ${{ inputs.stage_name }}
          changed-services: ${{ inputs.changed_services }}

      - name: Generate Code
        run: npx lerna run generate

      - name: Compile proto migration files
        run: npx lerna run build --scope=@managed-care-review/app-proto

      - name: upload app web gen directory
        uses: actions/upload-artifact@v3
        with:
          name: app-web-gen
          path: ./services/app-web/src/gen

      - name: upload cypress gen directory
        uses: actions/upload-artifact@v3
        with:
          name: cypress-gen
          path: ./services/cypress/gen

      - uses: actions/download-artifact@v3
        with:
          name: lambda-layers-prisma-client-migration
          path: ./services/app-api/lambda-layers-prisma-client-migration

      - name: Unzip prisma migration layer
        run: |
          tar -C ./services/app-api/lambda-layers-prisma-client-migration -xf ./services/app-api/lambda-layers-prisma-client-migration/nodejs.tar.gz
          rm -rf ./services/app-api/lambda-layers-prisma-client-migration/nodejs.tar.gz

      - uses: actions/download-artifact@v3
        with:
          name: lambda-layers-prisma-client-engine
          path: ./services/app-api/lambda-layers-prisma-client-engine

      - name: Unzip prisma engine layer
        run: |
          tar -C ./services/app-api/lambda-layers-prisma-client-engine -xf ./services/app-api/lambda-layers-prisma-client-engine/nodejs.tar.gz
          rm -rf ./services/app-api/lambda-layers-prisma-client-engine/nodejs.tar.gz

      - name: deploy app-api
        id: deploy-app-api
        env:
          NODE_OPTIONS: --max_old_space_size=6000
          APP_VERSION: ${{ inputs.app_version }}
          DATABASE_URL: AWS_SM
          REACT_APP_AUTH_MODE: ${{ secrets.react_app_auth_mode }}
          EMAILER_MODE: SES
          NR_LICENSE_KEY: ${{ secrets.nr_license_key }}
        run: |
          pushd services/app-api && npx serverless deploy --stage ${{ inputs.stage_name }}

      - name: run migrations
        id: run-migrations
        working-directory: services/app-api
        env:
          STAGE_NAME: ${{ inputs.stage_name }}
        run: |
          ./scripts/invoke-migrate-lambda.sh app-api-$STAGE_NAME-migrate
