name: Promote to an environment

on:
  workflow_call:
    inputs:
      stage_name:
        required: true
        type: string
      app_version:
        required: true
        type: string
      changed_services:
        required: true
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      aws_default_region:
        required: true
      iam_path:
        required: true
      ld_sdk_key:
        required: true
      react_app_auth_mode:
        required: true
      react_app_otel_collector_url:
        required: true

jobs:
  app-web:
    if: ${{ contains(inputs.changed_services, 'app-web') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup_env

      - name: Generate Code
        run: lerna run generate-code

      - name: deploy app-web
        id: deploy-app-web
        env:
          NODE_OPTIONS: --max_old_space_size=6000
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          AWS_DEFAULT_REGION: ${{ secrets.aws_default_region }}
          IAM_PATH: ${{ secrets.iam_path }}
          REACT_APP_AUTH_MODE: ${{ secrets.react_app_auth_mode }}

        run: |
          pushd services/app-web && npx serverless deploy --stage ${{ inputs.stage_name }}

  app-api:
    if: ${{ contains(inputs.changed_services, 'app-api') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup_env

      - name: Generate Code
        run: lerna run generate-code

      - uses: actions/download-artifact@v3
        with:
          name: lambda-layers-prisma-client-migration
          path: ./services/app-api/lambda-layers-prisma-client-migration

      - name: Unzip prisma migration layer
        run: |
          tar -C ./services/app-api/lambda-layers-prisma-client-migration -xf ./services/app-api/lambda-layers-prisma-client-migration/nodejs.tar.gz
          rm -rf ./services/app-api/lambda-layers-prisma-client-migration/nodejs.tar.gz

      - uses: actions/download-artifact@v3
        with:
          name: lambda-layers-prisma-client-engine
          path: ./services/app-api/lambda-layers-prisma-client-engine

      - name: Unzip prisma engine layer
        run: |
          tar -C ./services/app-api/lambda-layers-prisma-client-engine -xf ./services/app-api/lambda-layers-prisma-client-engine/nodejs.tar.gz
          rm -rf ./services/app-api/lambda-layers-prisma-client-engine/nodejs.tar.gz

      - name: deploy app-api
        id: deploy-app-api
        env:
          NODE_OPTIONS: --max_old_space_size=6000
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          AWS_DEFAULT_REGION: ${{ secrets.aws_default_region }}
          APP_VERSION: ${{ inputs.app_version }}
          DATABASE_URL: AWS_SM
          REACT_APP_AUTH_MODE: ${{ secrets.react_app_auth_mode }}
          IAM_PATH: ${{ secrets.iam_path }}
          EMAILER_MODE: SES
          REACT_APP_OTEL_COLLECTOR_URL: ${{ secrets.react_app_otel_collector_url }}
          LD_SDK_KEY: ${{ secrets.ld_sdk_key }}

        run: |
          pushd services/app-api && npx serverless deploy --stage ${{ inputs.stage_name }}

      - name: run migrations
        id: run-migrations
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          AWS_DEFAULT_REGION: ${{ secrets.aws_default_region }}
          STAGE_NAME: ${{ inputs.stage_name }}
        run: |
          pushd services/app-api && ./scripts/invoke-migrate-lambda.sh app-api-$STAGE_NAME-migrate
