name: Destroy

on: delete

permissions:
  id-token: write

jobs:
  destroy:
    # Protected branches should be designated as such in the GitHub UI.
    # So, a protected branch should never have this workflow run, since the branch should never be deleted.
    # This conditional is a backup mechanism to help prevent mistakes from becoming disasters.
    # This is a list of branch names that are commonly used for protected branches/environments.
    # Add/remove names from this list as appropriate.
    if: github.event.ref_type == 'branch' && !contains(fromJson('["develop", "main", "master", "impl", "val", "prod", "production"]'), github.event.ref)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set stage_name
        run: |
          echo "stage_name=$(./scripts/stage_name_for_branch.sh ${{ github.event.ref }})" >> $GITHUB_ENV

      - name: Setup env
        uses: ./.github/actions/setup_env

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region:  ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.DEV_OIDC_ROLE_ARN }}

      - name: build scripts
        shell: bash
        run: |
          lerna run build:ci-scripts

      - name: lock this branch to prevent concurrent destroys
        run: ./.github/github-lock.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: destroy all
        env:
          STAGE_PREFIX: ${{ secrets.STAGE_PREFIX }}
          # the default secrets.GITHUB_TOKEN granted to workflows won't suffice here
          # this script needs a personal access token with repo scope since it deletes GitHub secrets
          GITHUB_TOKEN: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}
        run: node ./scripts/destroy_stage.js $stage_name

      - name: Alert Slack On Destroy Failure
        uses: rtCamp/action-slack-notify@v2
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Destroy Alerts
          SLACK_ICON_EMOJI: ':bell:'
          SLACK_COLOR: ${{job.status}}
          SLACK_FOOTER: ''
          MSG_MINIMAL: actions url,commit,ref
