name: Send DSO metrics events

on:
  schedule:
    - cron: '0 * * * *'

permissions:
  id-token: write

jobs:
  SendDSOEvents:
    runs-on: ubuntu-latest
    steps:
      - name: Send DSO events
        uses: Enterprise-CMCS/mac-fc-scan-github@v1.0.1
        with:
          aws-account-id: ${{ secrets.DEV_AWS_ACCOUNT_ID }}
          oidc-role: arn:aws:iam::${{secrets.DEV_AWS_ACCOUNT_ID }}:role/delegatedadmin/developer/professor-mac-github-oidc
          github-access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          scan-config: |
            events:  # a list of event specifications such as the following one
            - type: deploy 
            name: mc-review-promote
            team: mv-review
            environment: prod
            owner: Enterprise-CMCS
            repo: managed-care-review
            workflowfilename: promote.yml
            branch: main
