name: Validate PRs

on:
  pull_request:
    branches:
      - main

jobs:
  validate-pr:
    name: Validate PR
    runs-on: ubuntu-20.04
    permissions:
      deployments: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: Setup env
        uses: ./.github/actions/setup_env

      - name: build scripts
        shell: bash
        run: |
          lerna run build:ci-scripts

      - name: DangerJS
        run: yarn danger ci
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

