Name: Validate PRs

on:
  pull_request:
    branches:
      - main

jobs:
  check-pr:
    name: Validate PRs
    runs-on: ubuntu-20.04
    permissions:
      deployments: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: DangerJS
        run: yarn danger ci
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

